import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Notifications from "@/components/Notifications";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container min-h-screen flex flex-col justify-between px-5 mx-auto">
          <Navbar />
          {children}
          <Notifications />
          <Footer />
        </div>
      </body>
    </html>
  );
}
